#ifndef FACEDETECTION_EXPORT_H
#define FACEDETECTION_EXPORT_H

// 静态库或源码集成时不需要 dllexport/dllimport
#define FACEDETECTION_EXPORT
#define FACEDETECTION_NO_EXPORT

// 废弃的宏定义（为了兼容）
#define FACEDETECTION_DEPRECATED
#define FACEDETECTION_DEPRECATED_EXPORT
#define FACEDETECTION_DEPRECATED_NO_EXPORT

#endif // FACEDETECTION_EXPORT_H
